# Generated by Django 5.2.17 on 2026-09-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wardrobe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("top", "👕 Top"),
                    ("bottom", "👖 Bottom"),
                    ("dress", "👗 Dress"),
                    ("outerwear", "🧥 Outerwear"),
                    ("shoes", "👟 Shoes"),
                    ("accessory", "👜 Accessory"),
                ],
                max_length=20,
            ),
        ),
    ]
