# Generated by Django 5.2.17 on 2026-09-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wardrobe", "0002_alter_item_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anthropic_api_key", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
