# Generated by Django 5.2.17 on 2026-09-10 15:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wardrobe", "0003_appsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worn_on", models.DateField(default=datetime.date.today)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wears",
                        to="wardrobe.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-worn_on", "-id"],
            },
        ),
    ]
